version: '3.8'
services:
  api:
    build: ./backend
    container_name: api
    ports:
      - '4000:4000'
    
  client:
    build: ./frontend
    container_name: client
    ports:
      - '3000:3000'
    depends_on:
      - api